# Generated by Django 3.1.6 on 2022-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='creditos_aprobados_semestre',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
