# Generated by Django 3.1.6 on 2021-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210508_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='cc',
            new_name='cedula_ciudadano',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_semestre',
            field=models.IntegerField(default=0),
        ),
    ]
