# Generated by Django 3.1.6 on 2021-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20210519_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='img'),
        ),
    ]
