# Generated by Django 3.1.6 on 2021-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_persona_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='institucional/'),
        ),
    ]
