# Generated by Django 3.1.6 on 2021-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20210601_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='institucional'),
        ),
    ]
