# Generated by Django 3.1.6 on 2021-07-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20210601_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
