# Generated by Django 3.1.6 on 2021-05-27 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0006_auto_20210519_1649'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecesora',
            fields=[
                ('id_antecesora', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de Asignatura')),
                ('creditos', models.IntegerField(default=None, verbose_name='Creditos')),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaUsuario',
            fields=[
                ('id_asignatura_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('matricula_realizada', models.BooleanField(default=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('id_cortes', models.AutoField(primary_key=True, serialize=False)),
                ('nota_corte1', models.IntegerField(default=0)),
                ('nota_corte2', models.IntegerField(default=0)),
                ('nota_corte3', models.IntegerField(default=0)),
                ('porcentaje_corte1_y_2', models.IntegerField(default=0.3, editable=False)),
                ('porcentaje_corte3', models.IntegerField(default=0.4, editable=False)),
                ('asignatura_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignaturausuario')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Facultad')),
                ('director', models.CharField(max_length=50, verbose_name='Nombre de Director')),
                ('telefono', models.IntegerField(default=None, verbose_name='Telefono de Facultad')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id_plan_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=0, max_length=50, verbose_name='Nombre del plan de estudio')),
                ('total_creditos', models.IntegerField(default=None, verbose_name='Creditos del programa')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos_permitidos', models.IntegerField(default=None, verbose_name='Creditos permitidos')),
                ('costo', models.IntegerField(default=None, verbose_name='Precio del semestre')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.planestudio')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del programa')),
                ('cantidad_semestres', models.SmallIntegerField(default=1, verbose_name='Semestres que tiene el programa')),
                ('telefono', models.IntegerField(default=None, verbose_name='Telefono')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='planestudio',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.programa'),
        ),
        migrations.CreateModel(
            name='PagoRecibo',
            fields=[
                ('id_pago_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(default=None, unique=True)),
                ('esta_pago', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.persona')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFinal',
            fields=[
                ('id_nota_final', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(default=0)),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignaturausuario')),
                ('cortes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.cortes')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAsignatura',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(blank=True)),
                ('hora_final', models.TimeField(blank=True, default=None)),
                ('dia_semana', models.CharField(blank=True, max_length=50, verbose_name='Dia de la semana')),
                ('Asignatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura')),
                ('docente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaAntecesora',
            fields=[
                ('id_asignatura_antecesora', models.AutoField(primary_key=True, serialize=False)),
                ('antecesora', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.antecesora')),
                ('asignatura', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.semestre'),
        ),
        migrations.AddField(
            model_name='antecesora',
            name='asignatura',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura'),
        ),
    ]
