# Generated by Django 3.1.6 on 2022-02-10 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorecibo',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.persona'),
        ),
        migrations.AddField(
            model_name='pagorecibo',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.semestre'),
        ),
        migrations.AddField(
            model_name='horarioasignatura',
            name='asignatura',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura'),
        ),
        migrations.AddField(
            model_name='horarioasignatura',
            name='dia_semana',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.diasemana'),
        ),
        migrations.AddField(
            model_name='horarioasignatura',
            name='docente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignaturausuario',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura'),
        ),
        migrations.AddField(
            model_name='asignaturausuario',
            name='horario_asignatura',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.horarioasignatura'),
        ),
        migrations.AddField(
            model_name='asignaturausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignaturaantecesora',
            name='antecesora',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.antecesora'),
        ),
        migrations.AddField(
            model_name='asignaturaantecesora',
            name='asignatura',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.semestre'),
        ),
        migrations.AddField(
            model_name='antecesora',
            name='asignatura',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura'),
        ),
    ]
