# Generated by Django 3.1.6 on 2021-05-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0004_auto_20210528_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturausuario',
            name='horario_asignatura',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.horarioasignatura'),
        ),
    ]
