# Generated by Django 3.1.6 on 2022-02-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0004_auto_20220223_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='antecesora',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura'),
        ),
    ]
