# Generated by Django 3.1.6 on 2021-06-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0005_auto_20210528_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id_dia_semana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dia', models.CharField(blank=True, max_length=40, verbose_name='Nombre Dia de la semana')),
            ],
        ),
        migrations.AlterField(
            model_name='horarioasignatura',
            name='dia_semana',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='institucional.diasemana'),
        ),
    ]
