# Generated by Django 3.1.6 on 2022-02-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0005_auto_20220223_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecesora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='antecesora',
        ),
        migrations.CreateModel(
            name='AsignaturaAntecesora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('antecesora', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institucional.antecesora')),
                ('asignatura', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='antecesora',
            name='asignatura',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='institucional.asignatura'),
        ),
    ]
