# Generated by Django 3.1.6 on 2021-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0006_auto_20210603_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioasignatura',
            name='dia_semana',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Dia de la semana'),
        ),
        migrations.DeleteModel(
            name='DiaSemana',
        ),
    ]
