# Generated by Django 3.1.6 on 2021-07-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0009_auto_20210708_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=70, verbose_name='Nombre del banco')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id_tarjeta_credito', models.AutoField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.BigIntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('codigo_seguridad', models.IntegerField(default=0)),
                ('credito_maximo', models.IntegerField(default=0)),
                ('propietario', models.CharField(max_length=70, verbose_name='Nombre del propietario')),
                ('esta_embargada', models.BooleanField(default=False)),
                ('banco', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institucional.bancos')),
            ],
        ),
    ]
